apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kubernetes/config.yaml
- kubernetes/deployment.yaml
- kubernetes/service.yaml
- kubernetes/postgres.yaml
images:
- name: django-image
  newName: replace-with-kustomize
