apiVersion: v1
kind: Service
metadata:
  name: django-boilerplate-service
  labels:
    app: django-app
spec:
  type: LoadBalancer
  selector:
    app: django-app
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8080
